apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniborrow-chat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uniborrow-chat
  template:
    metadata:
      labels:
        app: uniborrow-chat
    spec:
      containers:
        - image: lh5107/uniborrow-chat:2022-01-10-06-01-04
          name: uniborrow-chat
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://castor.db.elephantsql.com:5432/gdiwsvev
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: gdiwsvev
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uniborrow-chat-db-pass
                  key: password
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_SERVER_BASEURL
              value: http://uniborrow-chat:8085
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: uniborrow-cluster
            - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
              value: http://etcd:2379/health
            - name: KUMULUZEE_OPENAPIMP_UI_SPECIFICATIONSERVER
              value: http://35.223.79.242
          ports:
            - containerPort: 8085
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: uniborrow-chat
spec:
  type: ClusterIP
  ports:
    - port: 8085
  selector:
    app: uniborrow-chat