kumuluzee:
  name: uniborrow-chat-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-location: http://localhost:8085
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/ChatDB
      connection-url: jdbc:postgresql://localhost:5431/chat
      username: dbuser
      password: postgres
      pool:
        max-size: 1
  config:
    etcd:
      hosts: http://localhost:2379
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ChatDB
  metrics:
    servlet:
      enabled: true
      mapping: /metrics/*
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /metrics/*
        status-codes: "200, 500"
      - name: chat-endpoint
        url-pattren: /v1/chat/*
        status-codes: "200, 500"